name: just-create-change
on: 
  workflow_dispatch:
    inputs:
       incident:        
         description: 'Incident'
         required: true
         default: 'incident'
   
jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://dev65554.service-now.com/api/520575/testrest/getINC'
        method: 'GET'
        username: 'RestUser'
        password: 'BhindiBhaja@1'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"inc": "INC0000007"}'
    - name: Show Response  
      run:  |
       echo ${{ steps.myRequest.outputs.response }}
       //echo ${{ steps.myRequest.outputs.headers }}
       //echo ${{ fromJson(steps.myRequest.outputs.response).number}}
