name: first-wf
'on': workflow_dispatch
 inputs:
       start_date:        
         description: 'Change Start Date'
         required: true
         default: 'YYYY-MM-DDHH:MM:SS'
       end_date:
         description: 'Change End Date'
         required: true
         default: 'YYYY-MM-DDHH:MM:SS'

permissions:
  contents: read
   
jobs:
 deployment:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy Stage
      id: myRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: 'https://dev65554.service-now.com/api/520575/testrest/getINC'
        method: 'GET'
        username: 'RestUser'
        password: 'BhindiBhaja@1'
        customHeaders: '{"Content-Type": "application/json"}'
        data: '{"inc": "value_1"}'
    - name: Show Response  
      run:  |
       echo ${{ steps.myRequest.outputs.response }}
       //echo ${{ steps.myRequest.outputs.headers }}
       //echo ${{ fromJson(steps.myRequest.outputs.response).number}}
